name: Generate Podcast Feeds
on: [push]  #Whenever a push is done into the main branch the action will be automated 
jobs: #This is where we specify what we want to do
 build:
  runs-on: ubuntu-latest 
  steps:
   - name: Checkout Repo
     uses: actions/checkout@v3 #action versions
   - name: Setup Python
     uses: actions/setup-python@v4
     with:
      python-version: '3.10'
   - name: Install Dependencies 
     run: |
      python -m pip install --upgrade pip
      pip install pyyaml
   - name: Run Feed Generator
     run: python feed.py
   - name: Push Repo
     run: |
      git config user.name github-actions
      git config user.email github-actions@github.com
      git add .
      git commit -m "Modified Feed"
      git push

    
